# Generated by Django 3.2.11 on 2022-01-06 15:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('username', models.CharField(max_length=255, null=True)),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=users.models.content_file_name)),
                ('retrieve_password_otp', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitee_email', models.EmailField(max_length=254, null=True)),
                ('invitee_firstname', models.CharField(max_length=100, null=True)),
                ('invitee_lastname', models.CharField(max_length=100, null=True)),
                ('is_admin', models.BooleanField(null=True)),
                ('inviting_key', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_key', models.CharField(blank=True, max_length=100, null=True)),
                ('invited_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
                ('invite_expiry_date', models.DateTimeField(null=True, verbose_name='created')),
                ('invitation_status', models.CharField(choices=[('A', 'Accepted'), ('P', 'Pending')], default='P', max_length=10)),
                ('inviter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inviter', to='users.account')),
            ],
        ),
    ]
